# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  install_dependencies:
    docker: 
      - image: "circleci/node:16"
    steps:
      - checkout
      - run: yarn
      - persist_to_workspace:
          root: .
          paths: 
            - "*"

  log_files:
    docker: 
      - image: "circleci/node:16"
    steps: 
      - attach_workspace:
          at: .
      - run: ls -al
  
  run_tests:
    docker: 
      - image: "circleci/node:16"
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

  deploy_to_githubio:
    docker: 
      - image: "circleci/node:16"
    description: Use gh-pages package to deploy to github.io
    steps:
      - run: mkdir -p ~/.ssh                                   # prevents from 
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts      # "The authenticity of host 'github.com (140.82.113.4)' can't be established"
      - run: git config user.email "banach.krystian@gmail.com" # error while trying to push to gh-pages
      - run: git config user.name "CI gh-pages bot"            #
      - add_ssh_keys:
          fingerprints:
            - "59:ad:fd:64:71:eb:81:01:6a:d7:1a:c9:0c:19:39:af"
      - attach_workspace:
          at: .
      - run: yarn deploy

workflows:
  test_and_deploy:
    jobs:
      - install_dependencies
      - log_files:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - deploy_to_githubio:
          requires:
            - install_dependencies
            - run_tests
          # filters:
          #   branches:
          #     only: /master/
