# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  install_dependencies:
    docker: 
      - image: "circleci/node:16"
    steps:
      - checkout
      - run: yarn
      - persist_to_workspace:
          root: .
          paths: 
            - "*"

  log_files:
    docker: 
      - image: "circleci/node:16"
    steps: 
      - attach_workspace:
          at: .
      - run: ls -al
  
  run_tests:
    docker: 
      - image: "circleci/node:16"
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

  deploy_to_githubio:
    docker: 
      - image: "circleci/node:16"
    description: Use gh-pages package to deploy to github.io
    steps:
      - run: mkdir -p ~/.ssh                                            # prevents from 
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts               # "The authenticity of host 'github.com (140.82.113.4)' can't be established"
      - run: git config --global user.email "banach.krystian@gmail.com" # error while trying to push to gh-pages
      - run: git config --global user.name "CI gh-pages bot"            #
      - add_ssh_keys:
          fingerprints:
            - "04:2d:53:38:f4:07:e1:66:8e:b3:01:c1:a4:1a:4a:d2"
      - attach_workspace:
          at: .
      - run:
        name: Add REACT_APP_BUILD_TIME variable
        command: |
          echo 'export REACT_APP_BUILD_TIME=$(date +"%Y-%m-%d - %H:%M:%S")' >> $BASH_ENV
          source $BASH_ENV
      - run: yarn deploy

workflows:
  test_and_deploy:
    jobs:
      - install_dependencies
      - log_files:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - deploy_to_githubio:
          requires:
            - install_dependencies
            - run_tests
          # filters:
          #   branches:
          #     only: /master/
