# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  yarn_install:
    docker: 
      - image: "circleci/node:16"
    steps:
      - run: yarn
  test:
    docker: 
      - image: "circleci/node:16"
    steps:
      - run: yarn test
  deploy_to_githubio:
    docker: 
      - image: "circleci/node:16"
    description: Use gh-pages package to deploy to github.io
    steps:
      - run: yarn deploy
      # filters:
      #   branches:
      #     only: /master/

workflows:
  test_and_deploy:
    jobs:
      - yarn_install
      - test
      - deploy_to_githubio
  

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   build: # This is the name of the workflow, feel free to change it to better match your workflow.
#     # Inside the workflow, you define the jobs you want to run.
#     jobs:
#       - node/test:
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
#           version: '16.10'
#           # If you are using yarn, change the line below from "npm" to "yarn"
#           pkg-manager: yarn